ARG SKIP_TESTS=false

FROM node:{{ getenv "ENGINE_VERSION" }}-alpine as builder

WORKDIR /app

# Dependency
COPY package*.json ./
RUN npm install

# Source code
COPY . .

# Tests
RUN if [ "$SKIP_TESTS" = "false" ] ; then \
        apk add --no-cache chromium chromium-chromedriver && \
        export CHROME_BIN=/usr/bin/chromium-browser && \
        npm run lint && \
        npm run stylelint && \
        npm run coverage && \
        npm run test && \
        npm run e2e ; \
    fi

# Build
RUN npm run build-docker

# --- Final image -------------------------------------
FROM nginx:stable-alpine-slim

COPY --from=builder /app/dist/* /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
