formatter: "markdown"

version: ">= 0.13.0, < 1.0.0"

sections:
  show-all: true

recursive:
  enabled: true
  path: modules
  include-main: true

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  indent: 3
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
