apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greencity
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/apps
    repoURL: https://github.com/PTarasyuk/greencityinfra
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
