name: CI/CD for front app (using reusable workflow)

on:
  push:
  workflow_dispatch:
# on:
#   push:
#     tags:
#       - 'v*.*.*'

jobs:
  ci-cd:
    uses: PTarasyuk/GreenCityInfra/.github/workflows/app-ci-cd.yaml@main
    with:
      app_name: 'front'
      engine_type: 'node'
      engine_version: '14'
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
