name: CI/CD for front app (using reusable workflow)

on: push
# on:
#   push:
#     tags:
#       - 'v*.*.*'

jobs:
  ci-cd:
    uses: PTarasyuk/GreenCityInfra/ci-cd/workflows/main.yml@main
    with:
      app_name: 'front'
      app_version: "${{ github.ref_name || 'v0.0.0' }}-${{ github.sha.slice(0, 7) }}"
      engine_type: 'node'
      engine_version: '14'
