name: CI/CD for user app (using reusable workflow)

on:
  push:
  workflow_dispatch:
# on:
#   push:
#     tags:
#       - 'v*.*.*'

jobs:
  ci-cd:
    uses: PTarasyuk/GreenCityInfra/.github/workflows/app-ci-cd.yaml@main
    with:
      app_name: 'user'
      engine_type: 'java'
      engine_version: '21'
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
