apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greencity

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  environment: ci-kind

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base

images:
- name: postgres
  newTag: 15-alpine
- name: ghcr.io/ptarasyuk/greencityinfra/core
  newTag: v0.0.1-d90e082
- name: ghcr.io/ptarasyuk/greencityinfra/front
  newTag: v0.0.0-fb3b45f
- name: ghcr.io/ptarasyuk/greencityinfra/user
  newTag: v0.0.3-0fc7ebd

secretGenerator:
- name: db-secrets
  envs:
  - envs/.db.env
- name: core-secrets
  envs:
  - envs/.core.env
- name: user-secrets
  envs:
  - envs/.user.env
- name: common-secrets
  envs:
  - envs/.common.env

configMapGenerator:
- files:
  - nginx.conf=nginx/default.conf
  name: nginx-config

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: api.greencity.local
  target:
    kind: Ingress
    name: api-ingress

- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: greencity.local
  target:
    kind: Ingress
    name: front-ingress

- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0
      value:
        name: db-storage
        emptyDir: {}
  target:
    kind: StatefulSet
    name: db
