apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api/core/deployment.yaml
  - api/core/service.yaml
  - api/user/deployment.yaml
  - api/user/service.yaml
  - api/ingress.yaml
  - db/stateful.yaml
  - db/service.yaml
  - db/pvc.yaml
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
  - namespace.yaml
  - network-policy.yaml
  - rbac.yaml
