ARG SKIP_TESTS=false

FROM eclipse-temurin:{{ getenv "ENGINE_VERSION" }} AS builder

WORKDIR /build

# Install required packages
RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

# Copy only pom.xml files first for dependency caching
COPY pom.xml .
COPY core/pom.xml core/
COPY dao/pom.xml dao/
COPY service/pom.xml service/
COPY service-api/pom.xml service-api/

# Download dependencies
RUN mvn dependency:go-offline

# Copy source code
COPY core/src core/src
COPY dao/src dao/src
COPY service/src service/src
COPY service-api/src service-api/src

# Run tests if not skipped
RUN if [ "$SKIP_TESTS" = "false" ] ; then \
      mvn test \
      -Dformatter.skip=true \
      -Dcheckstyle.skip=true \
    ; fi

# Build
RUN mvn package \
    -DskipTests=true \
    -Dformatter.skip=true \
    -Dcheckstyle.skip=true


# --- Final image -------------------------------------
FROM eclipse-temurin:{{ getenv "ENGINE_VERSION" }}-jre-alpine

WORKDIR /opt/app
COPY --from=builder /build/core/target/core.jar app.jar

ENV PROFILE=docker
ENV JAVA_OPTS="-Xmx512m -Xms256m -XX:+UseContainerSupport"

ENTRYPOINT ["java", "-jar", "/opt/app/app.jar"]