name: Reusable App Build and Dockerize

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      engine_type: # java or node
        required: true
        type: string
      engine_version:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          path: app-repo

      - name: Checkout infrastructure repo
        uses: actions/checkout@v4
        with:
          repository: 'PTarasyuk/GreenCityInfra'
          path: infra-repo

      - name: Get App Version
        run: |
          git -C app-repo fetch --tags
          TAG=$(git -C ./app-repo tag | sort -V | tail -n 1)
          if [ -z "$TAG" ]; then
            TAG="v0.0.0"
          fi
          SHORT_SHA=$(git -C ./app-repo rev-parse --short HEAD)
          APP_VERSION=${TAG}-${SHORT_SHA}
          echo "APP_VERSION: ${APP_VERSION}"
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      - name: Render Dockerfile
        env:
          ENGINE_VERSION: ${{ inputs.engine_version }}
        run: |
          wget https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64
          chmod +x confd-0.16.0-linux-amd64
          sudo mv confd-0.16.0-linux-amd64 /usr/local/bin/confd
          confd -onetime \
                -backend env \
                -confdir infra-repo/ci-cd/confd/${{ inputs.engine_type }}
          mv /tmp/Dockerfile ./app-repo/Dockerfile

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg SKIP_TESTS=false \
            -t ghcr.io/ptarasyuk/greencityinfra/${{ inputs.app_name }}:$APP_VERSION \
            -f ./app-repo/Dockerfile \
            ./app-repo

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/ptarasyuk/greencityinfra/${{ inputs.app_name }}:$APP_VERSION

      - name: Update `image.tag` in `values.yaml`
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(APP_VERSION)' infra-repo/helm/${{ inputs.app_name }}/values.yaml

      - name: Create PR to infrastructure repository
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          path: infra-repo
          base: main
          branch: ${{ inputs.app_name }}-$APP_VERSION
          commit-message: '✨ feat(${{ inputs.app_name }}): new version $APP_VERSION'
          delete-branch: true
          title: '✨ New version!'
          body: |
            # New version of the `${{ inputs.app_name }}` application `$APP_VERSION`!

            ## Description

            This PR updates the `${{ inputs.app_name }}` application to version `$APP_VERSION`.

            ## Changes

            - Changed the value of the `image.tag` variable in `helm/${{ inputs.app_name }}/values.yaml` to `$APP_VERSION`
