name: CI/CD for App

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      engine_type:
        required: true
        type: string
      engine_version:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  ci-cd:
    uses: ci-cd/workflows/main.yaml
    with:
      app_name: ${{ inputs.app_name }}
      engine_type: ${{ inputs.engine_type }}
      engine_version: ${{ inputs.engine_version }}
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}