apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front.fullname" . }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
data:
  nginx-conf: |
    {{- .Files.Get "nginx.conf" | nindent 4 }}
